# YouTube Channel Metadata Extraction

This notebook pulls as much public metadata as the YouTube Data API v3 provides for every video on a channel.

It supports a channel handle (for example `@thetenurefacility`), a channel URL, or a channel ID.

## 1. Install dependencies

In [1]:
!pip install -q google-api-python-client pandas

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

## 2. Config

Set your YouTube API key and the channel you want to query.

In [2]:
API_KEY = "AIzaSyDLuW8Q7rCzOyHyAW1fSqTAMiBmpaLCmis"
CHANNEL_INPUT = "@thetenurefacility"  # can be @handle, channel ID, or channel URL
REGION_CODE = "US"
SAVE_PREFIX = "tenure_facility"

## 3. Imports and API client

In [3]:
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
import pandas as pd
import json
import re
from typing import List, Dict, Any, Optional

youtube = build("youtube", "v3", developerKey=API_KEY)

## 4. Helpers

In [4]:
def chunks(lst, n):
    for i in range(0, len(lst), n):
        yield lst[i:i+n]


def clean_text(x):
    if x is None:
        return None
    return str(x).replace("\r\n", "\n").replace("\r", "\n").strip()


def extract_channel_id_from_url(url: str) -> Optional[str]:
    m = re.search(r"/channel/([A-Za-z0-9_-]+)", url)
    return m.group(1) if m else None


def extract_handle_from_url(url: str) -> Optional[str]:
    m = re.search(r"youtube\.com/@([A-Za-z0-9._-]+)", url)
    return f"@{m.group(1)}" if m else None


def normalize_channel_input(channel_input: str) -> Dict[str, str]:
    channel_input = channel_input.strip()
    if channel_input.startswith("@"):
        return {"type": "handle", "value": channel_input}
    if "youtube.com/" in channel_input:
        channel_id = extract_channel_id_from_url(channel_input)
        if channel_id:
            return {"type": "id", "value": channel_id}
        handle = extract_handle_from_url(channel_input)
        if handle:
            return {"type": "handle", "value": handle}
    if re.fullmatch(r"UC[a-zA-Z0-9_-]{22}", channel_input):
        return {"type": "id", "value": channel_input}
    return {"type": "handle", "value": channel_input}

## 5. Resolve the channel and get the uploads playlist

In [5]:
def get_channel_resource(channel_input: str) -> Dict[str, Any]:
    parsed = normalize_channel_input(channel_input)

    common_parts = (
        "snippet,contentDetails,statistics,brandingSettings,status,topicDetails,localizations"
    )

    if parsed["type"] == "handle":
        resp = youtube.channels().list(
            part=common_parts,
            forHandle=parsed["value"]
        ).execute()
    else:
        resp = youtube.channels().list(
            part=common_parts,
            id=parsed["value"]
        ).execute()

    items = resp.get("items", [])
    if not items:
        raise ValueError(f"No channel found for input: {channel_input}")

    return items[0]


channel_resource = get_channel_resource(CHANNEL_INPUT)
channel_id = channel_resource["id"]
uploads_playlist_id = channel_resource["contentDetails"]["relatedPlaylists"]["uploads"]

print("Channel ID:", channel_id)
print("Uploads playlist:", uploads_playlist_id)
print("Title:", channel_resource["snippet"].get("title"))

Channel ID: UC486iX5Pijix88cRP6KIcng
Uploads playlist: UU486iX5Pijix88cRP6KIcng
Title: Tenure Facility

## 6. Pull all upload entries from the uploads playlist

In [6]:
def get_all_playlist_items(playlist_id: str) -> List[Dict[str, Any]]:
    all_items = []
    next_page_token = None

    while True:
        resp = youtube.playlistItems().list(
            part="id,snippet,contentDetails,status",
            playlistId=playlist_id,
            maxResults=50,
            pageToken=next_page_token
        ).execute()

        all_items.extend(resp.get("items", []))
        next_page_token = resp.get("nextPageToken")

        if not next_page_token:
            break

    return all_items


playlist_items = get_all_playlist_items(uploads_playlist_id)
video_ids = [
    item["contentDetails"]["videoId"]
    for item in playlist_items
    if item.get("contentDetails", {}).get("videoId")
]

print("Playlist items fetched:", len(playlist_items))
print("Video IDs fetched:", len(video_ids))

Playlist items fetched: 148
Video IDs fetched: 148

## 7. Pull category lookup table

In [7]:
def get_video_categories(region_code: str = "US") -> Dict[str, str]:
    resp = youtube.videoCategories().list(
        part="snippet",
        regionCode=region_code
    ).execute()

    out = {}
    for item in resp.get("items", []):
        out[item["id"]] = item.get("snippet", {}).get("title")
    return out


category_map = get_video_categories(REGION_CODE)
list(category_map.items())[:10]

[('1', 'Film & Animation'),
 ('2', 'Autos & Vehicles'),
 ('10', 'Music'),
 ('15', 'Pets & Animals'),
 ('17', 'Sports'),
 ('18', 'Short Movies'),
 ('19', 'Travel & Events'),
 ('20', 'Gaming'),
 ('21', 'Videoblogging'),
 ('22', 'People & Blogs')]

## 8. Pull rich video metadata for every video

In [8]:
def get_all_videos(video_ids: List[str]) -> List[Dict[str, Any]]:
    all_videos = []

    for batch in chunks(video_ids, 50):
        resp = youtube.videos().list(
            part="snippet,contentDetails,statistics,status,topicDetails,liveStreamingDetails,localizations,recordingDetails",
            id=",".join(batch),
            maxResults=50
        ).execute()

        all_videos.extend(resp.get("items", []))

    return all_videos


video_resources = get_all_videos(video_ids)
print("Video resources returned:", len(video_resources))

Video resources returned: 148

## 9. Flatten the channel metadata

In [9]:
def flatten_channel(channel: Dict[str, Any]) -> Dict[str, Any]:
    snippet = channel.get("snippet", {})
    stats = channel.get("statistics", {})
    branding = channel.get("brandingSettings", {})
    status = channel.get("status", {})
    topics = channel.get("topicDetails", {})

    thumbs = snippet.get("thumbnails", {})

    return {
        "channel_id": channel.get("id"),
        "channel_title": snippet.get("title"),
        "channel_description": clean_text(snippet.get("description")),
        "channel_custom_url": snippet.get("customUrl"),
        "channel_published_at": snippet.get("publishedAt"),
        "channel_country": snippet.get("country"),
        "channel_view_count": stats.get("viewCount"),
        "channel_subscriber_count": stats.get("subscriberCount"),
        "channel_hidden_subscriber_count": stats.get("hiddenSubscriberCount"),
        "channel_video_count": stats.get("videoCount"),
        "channel_keywords": branding.get("channel", {}).get("keywords"),
        "channel_tracking_analytics_account_id": branding.get("channel", {}).get("trackingAnalyticsAccountId"),
        "channel_unsubscribed_trailer": branding.get("channel", {}).get("unsubscribedTrailer"),
        "channel_default_language": branding.get("channel", {}).get("defaultLanguage"),
        "channel_made_for_kids": status.get("madeForKids"),
        "channel_self_declared_made_for_kids": status.get("selfDeclaredMadeForKids"),
        "channel_topic_categories": json.dumps(topics.get("topicCategories", []), ensure_ascii=False),
        "channel_thumb_default": thumbs.get("default", {}).get("url"),
        "channel_thumb_medium": thumbs.get("medium", {}).get("url"),
        "channel_thumb_high": thumbs.get("high", {}).get("url"),
    }


channel_flat = flatten_channel(channel_resource)
channel_flat

{'channel_id': 'UC486iX5Pijix88cRP6KIcng',
 'channel_title': 'Tenure Facility',
 'channel_description': 'More than 2.5 billion Indigenous Peoples and local communities live in almost half of the world’s land area, yet they legally own less than 10% of their territories. These richly biodiverse ancestral lands are vital to our global climate, fresh water and food security. When land rights aren’t legally recognised, it puts lives and ecosystems at risk. Reducing land conflict, advancing human rights, promoting development and contributing to sustainable climate solutions can all start with strengthening community tenure rights. The Tenure Facility works alongside Indigenous Peoples and local communities, offering dedicated financial and technical support for innovative approaches to implementing collective tenure rights, whilst sharing the knowledge, innovations and tools that emerge across a global network.',
 'channel_custom_url': '@thetenurefacility',
 'channel_published_at': '2018-01-23T19:26:57Z',
 'channel_country': 'SE',
 'channel_view_count': '12537',
 'channel_subscriber_count': '176',
 'channel_hidden_subscriber_count': False,
 'channel_video_count': '148',
 'channel_keywords': None,
 'channel_tracking_analytics_account_id': None,
 'channel_unsubscribed_trailer': 'EhioEX10DNo',
 'channel_default_language': None,
 'channel_made_for_kids': None,
 'channel_self_declared_made_for_kids': None,
 'channel_topic_categories': '["https://en.wikipedia.org/wiki/Knowledge", "https://en.wikipedia.org/wiki/Society"]',
 'channel_thumb_default': 'https://yt3.ggpht.com/lY5opk8UFslyNRpQmxL2whl6urjsauzF4P_hB28EvQE8j3iBS3YAMLbUIPgHLBY0n5enmXhAKA=s88-c-k-c0x00ffffff-no-rj',
 'channel_thumb_medium': 'https://yt3.ggpht.com/lY5opk8UFslyNRpQmxL2whl6urjsauzF4P_hB28EvQE8j3iBS3YAMLbUIPgHLBY0n5enmXhAKA=s240-c-k-c0x00ffffff-no-rj',
 'channel_thumb_high': 'https://yt3.ggpht.com/lY5opk8UFslyNRpQmxL2whl6urjsauzF4P_hB28EvQE8j3iBS3YAMLbUIPgHLBY0n5enmXhAKA=s800-c-k-c0x00ffffff-no-rj'}

## 10. Build a playlist-item lookup

In [10]:
playlist_lookup = {}
for item in playlist_items:
    vid = item.get("contentDetails", {}).get("videoId")
    if not vid:
        continue
    playlist_lookup[vid] = {
        "playlist_item_id": item.get("id"),
        "playlist_position": item.get("snippet", {}).get("position"),
        "playlist_video_published_at": item.get("contentDetails", {}).get("videoPublishedAt"),
        "playlist_privacy_status": item.get("status", {}).get("privacyStatus"),
    }

len(playlist_lookup)

148

## 11. Flatten each video

In [11]:
def pick_thumbnail(thumbnails: Dict[str, Any], key: str) -> Optional[str]:
    return thumbnails.get(key, {}).get("url")


def flatten_video(video: Dict[str, Any], category_map: Dict[str, str], playlist_lookup: Dict[str, Dict[str, Any]], channel_flat: Dict[str, Any]) -> Dict[str, Any]:
    snippet = video.get("snippet", {})
    content = video.get("contentDetails", {})
    stats = video.get("statistics", {})
    status = video.get("status", {})
    topics = video.get("topicDetails", {})
    live = video.get("liveStreamingDetails", {})
    recording = video.get("recordingDetails", {})
    localizations = video.get("localizations", {})
    thumbs = snippet.get("thumbnails", {})

    vid = video.get("id")
    playlist_meta = playlist_lookup.get(vid, {})

    out = {}
    out.update(channel_flat)
    out.update({
        "video_id": vid,
        "video_url": f"https://www.youtube.com/watch?v={vid}",

        "title": snippet.get("title"),
        "description": clean_text(snippet.get("description")),
        "published_at": snippet.get("publishedAt"),
        "default_language": snippet.get("defaultLanguage"),
        "default_audio_language": snippet.get("defaultAudioLanguage"),
        "channel_id_from_video": snippet.get("channelId"),
        "channel_title_from_video": snippet.get("channelTitle"),
        "category_id": snippet.get("categoryId"),
        "category_title": category_map.get(snippet.get("categoryId")),
        "tags": json.dumps(snippet.get("tags", []), ensure_ascii=False),
        "live_broadcast_content": snippet.get("liveBroadcastContent"),

        "thumb_default": pick_thumbnail(thumbs, "default"),
        "thumb_medium": pick_thumbnail(thumbs, "medium"),
        "thumb_high": pick_thumbnail(thumbs, "high"),
        "thumb_standard": pick_thumbnail(thumbs, "standard"),
        "thumb_maxres": pick_thumbnail(thumbs, "maxres"),

        "duration_iso8601": content.get("duration"),
        "dimension": content.get("dimension"),
        "definition": content.get("definition"),
        "caption": content.get("caption"),
        "licensed_content": content.get("licensedContent"),
        "projection": content.get("projection"),
        "content_rating": json.dumps(content.get("contentRating", {}), ensure_ascii=False),
        "region_restriction": json.dumps(content.get("regionRestriction", {}), ensure_ascii=False),

        "upload_status": status.get("uploadStatus"),
        "privacy_status": status.get("privacyStatus"),
        "license": status.get("license"),
        "embeddable": status.get("embeddable"),
        "public_stats_viewable": status.get("publicStatsViewable"),
        "made_for_kids": status.get("madeForKids"),
        "self_declared_made_for_kids": status.get("selfDeclaredMadeForKids"),

        "view_count": stats.get("viewCount"),
        "like_count": stats.get("likeCount"),
        "favorite_count": stats.get("favoriteCount"),
        "comment_count": stats.get("commentCount"),

        "topic_categories": json.dumps(topics.get("topicCategories", []), ensure_ascii=False),
        "topic_ids": json.dumps(topics.get("topicIds", []), ensure_ascii=False),

        "scheduled_start_time": live.get("scheduledStartTime"),
        "actual_start_time": live.get("actualStartTime"),
        "actual_end_time": live.get("actualEndTime"),
        "concurrent_viewers": live.get("concurrentViewers"),

        "recording_date": recording.get("recordingDate"),
        "recording_location_description": recording.get("locationDescription"),
        "recording_location": json.dumps(recording.get("location", {}), ensure_ascii=False),

        "localizations_json": json.dumps(localizations, ensure_ascii=False),

        "playlist_item_id": playlist_meta.get("playlist_item_id"),
        "playlist_position": playlist_meta.get("playlist_position"),
        "playlist_video_published_at": playlist_meta.get("playlist_video_published_at"),
        "playlist_privacy_status": playlist_meta.get("playlist_privacy_status"),
    })
    return out


rows = [flatten_video(v, category_map, playlist_lookup, channel_flat) for v in video_resources]
df = pd.DataFrame(rows)
df.head()

,channel_id,channel_title,channel_description,channel_custom_url,channel_published_at,channel_country,channel_view_count,channel_subscriber_count,channel_hidden_subscriber_count,channel_video_count,...,actual_end_time,concurrent_viewers,recording_date,recording_location_description,recording_location,localizations_json,playlist_item_id,playlist_position,playlist_video_published_at,playlist_privacy_status
0,UC486iX5Pijix88cRP6KIcng,Tenure Facility,More than 2.5 billion Indigenous Peoples and l...,@thetenurefacility,2018-01-23T19:26:57Z,SE,12537,176,False,148,...,2026-01-27T16:31:46Z,None,None,None,{},"{""en"": {""title"": ""The Belém Call: Mobilizing F...",VVU0ODZpWDVQaWppeDg4Y1JQNktJY25nLjhkQ2hFSmEtT3I4,0,2026-01-28T04:50:10Z,public
1,UC486iX5Pijix88cRP6KIcng,Tenure Facility,More than 2.5 billion Indigenous Peoples and l...,@thetenurefacility,2018-01-23T19:26:57Z,SE,12537,176,False,148,...,2025-07-17T14:13:38Z,None,None,None,{},"{""en"": {""title"": ""Indigenous NDCs for Climate ...",VVU0ODZpWDVQaWppeDg4Y1JQNktJY25nLmMzWVBZSWFjWlRB,1,2025-07-18T02:22:17Z,public
2,UC486iX5Pijix88cRP6KIcng,Tenure Facility,More than 2.5 billion Indigenous Peoples and l...,@thetenurefacility,2018-01-23T19:26:57Z,SE,12537,176,False,148,...,None,None,None,None,{},"{""en"": {""title"": ""Why are common reporting sta...",VVU0ODZpWDVQaWppeDg4Y1JQNktJY25nLlNhTF9taTN5U2xJ,2,2025-01-27T09:38:59Z,public
3,UC486iX5Pijix88cRP6KIcng,Tenure Facility,More than 2.5 billion Indigenous Peoples and l...,@thetenurefacility,2018-01-23T19:26:57Z,SE,12537,176,False,148,...,None,None,None,None,{},"{""en"": {""title"": ""Why are organisational finan...",VVU0ODZpWDVQaWppeDg4Y1JQNktJY25nLmp0dHFvdW9zTkZN,3,2025-01-24T08:29:08Z,public
4,UC486iX5Pijix88cRP6KIcng,Tenure Facility,More than 2.5 billion Indigenous Peoples and l...,@thetenurefacility,2018-01-23T19:26:57Z,SE,12537,176,False,148,...,None,None,None,None,{},"{""en"": {""title"": ""What is the meaning that the...",VVU0ODZpWDVQaWppeDg4Y1JQNktJY25nLjBOWmtUY0twWVJF,4,2024-07-23T07:26:38Z,public

In [12]:
import re
import json
import pandas as pd

# --- country dictionary ---
# Add or edit aliases as needed for your content.
COUNTRY_ALIASES = {
    "Afghanistan": ["afghanistan", "afghan"],
    "Albania": ["albania", "albanian"],
    "Algeria": ["algeria", "algerian"],
    "Angola": ["angola", "angolan"],
    "Argentina": ["argentina", "argentine", "argentinian"],
    "Australia": ["australia", "australian"],
    "Austria": ["austria", "austrian"],
    "Bangladesh": ["bangladesh", "bangladeshi"],
    "Belgium": ["belgium", "belgian"],
    "Belize": ["belize", "belizean"],
    "Benin": ["benin", "beninese"],
    "Bhutan": ["bhutan", "bhutanese"],
    "Bolivia": ["bolivia", "bolivian"],
    "Bosnia and Herzegovina": ["bosnia", "bosnian", "bosnia and herzegovina"],
    "Botswana": ["botswana", "botswanan"],
    "Brazil": ["brazil", "brazilian"],
    "Brunei": ["brunei", "bruneian"],
    "Bulgaria": ["bulgaria", "bulgarian"],
    "Burkina Faso": ["burkina faso", "burkinabe"],
    "Burundi": ["burundi", "burundian"],
    "Cambodia": ["cambodia", "cambodian"],
    "Cameroon": ["cameroon", "cameroonian"],
    "Canada": ["canada", "canadian"],
    "Central African Republic": ["central african republic"],
    "Chad": ["chad", "chadian"],
    "Chile": ["chile", "chilean"],
    "China": ["china", "chinese", "prc"],
    "Colombia": ["colombia", "colombian"],
    "Congo": ["republic of the congo", "congo-brazzaville"],
    "Democratic Republic of the Congo": [
        "democratic republic of the congo", "drc", "dr congo", "congo kinshasa", "congo-kinshasa"
    ],
    "Costa Rica": ["costa rica", "costa rican"],
    "Côte d’Ivoire": ["cote d’ivoire", "cote d'ivoire", "ivory coast", "ivoirian"],
    "Croatia": ["croatia", "croatian"],
    "Cuba": ["cuba", "cuban"],
    "Czechia": ["czechia", "czech republic", "czech"],
    "Denmark": ["denmark", "danish"],
    "Dominican Republic": ["dominican republic"],
    "Ecuador": ["ecuador", "ecuadorean", "ecuadorian"],
    "Egypt": ["egypt", "egyptian"],
    "El Salvador": ["el salvador", "salvadoran"],
    "Eritrea": ["eritrea", "eritrean"],
    "Estonia": ["estonia", "estonian"],
    "Eswatini": ["eswatini", "swaziland", "swazi"],
    "Ethiopia": ["ethiopia", "ethiopian"],
    "Fiji": ["fiji", "fijian"],
    "Finland": ["finland", "finnish"],
    "France": ["france", "french"],
    "Gabon": ["gabon", "gabonese"],
    "Gambia": ["gambia", "gambian"],
    "Georgia": ["georgia", "georgian"],
    "Germany": ["germany", "german"],
    "Ghana": ["ghana", "ghanaian"],
    "Greece": ["greece", "greek"],
    "Guatemala": ["guatemala", "guatemalan"],
    "Guinea": ["guinea", "guinean"],
    "Guyana": ["guyana", "guyanese"],
    "Haiti": ["haiti", "haitian"],
    "Honduras": ["honduras", "honduran"],
    "Hungary": ["hungary", "hungarian"],
    "Iceland": ["iceland", "icelandic"],
    "India": ["india", "indian"],
    "Indonesia": ["indonesia", "indonesian"],
    "Iran": ["iran", "iranian"],
    "Iraq": ["iraq", "iraqi"],
    "Ireland": ["ireland", "irish"],
    "Israel": ["israel", "israeli"],
    "Italy": ["italy", "italian"],
    "Jamaica": ["jamaica", "jamaican"],
    "Japan": ["japan", "japanese"],
    "Jordan": ["jordan", "jordanian"],
    "Kazakhstan": ["kazakhstan", "kazakh", "kazakhstani"],
    "Kenya": ["kenya", "kenyan"],
    "Kyrgyzstan": ["kyrgyzstan", "kyrgyz", "kyrgyzstani"],
    "Laos": ["laos", "lao", "laotian"],
    "Latvia": ["latvia", "latvian"],
    "Lebanon": ["lebanon", "lebanese"],
    "Liberia": ["liberia", "liberian"],
    "Libya": ["libya", "libyan"],
    "Lithuania": ["lithuania", "lithuanian"],
    "Luxembourg": ["luxembourg", "luxembourgish"],
    "Madagascar": ["madagascar", "malagasy"],
    "Malawi": ["malawi", "malawian"],
    "Malaysia": ["malaysia", "malaysian"],
    "Mali": ["mali", "malian"],
    "Mauritania": ["mauritania", "mauritanian"],
    "Mexico": ["mexico", "mexican"],
    "Moldova": ["moldova", "moldovan"],
    "Mongolia": ["mongolia", "mongolian"],
    "Montenegro": ["montenegro", "montenegrin"],
    "Morocco": ["morocco", "moroccan"],
    "Mozambique": ["mozambique", "mozambican"],
    "Myanmar": ["myanmar", "burma", "burmese"],
    "Namibia": ["namibia", "namibian"],
    "Nepal": ["nepal", "nepalese"],
    "Netherlands": ["netherlands", "dutch", "holland"],
    "New Zealand": ["new zealand", "new zealander", "kiwi"],
    "Nicaragua": ["nicaragua", "nicaraguan"],
    "Niger": ["niger", "nigerien"],
    "Nigeria": ["nigeria", "nigerian"],
    "North Macedonia": ["north macedonia", "macedonia", "macedonian"],
    "Norway": ["norway", "norwegian"],
    "Pakistan": ["pakistan", "pakistani"],
    "Panama": ["panama", "panamanian"],
    "Papua New Guinea": ["papua new guinea", "png"],
    "Paraguay": ["paraguay", "paraguayan"],
    "Peru": ["peru", "peruvian"],
    "Philippines": ["philippines", "philippine", "filipino", "filipina"],
    "Poland": ["poland", "polish"],
    "Portugal": ["portugal", "portuguese"],
    "Romania": ["romania", "romanian"],
    "Russia": ["russia", "russian"],
    "Rwanda": ["rwanda", "rwandan"],
    "Saudi Arabia": ["saudi arabia", "saudi"],
    "Senegal": ["senegal", "senegalese"],
    "Serbia": ["serbia", "serbian"],
    "Sierra Leone": ["sierra leone", "sierra leonean"],
    "Slovakia": ["slovakia", "slovak"],
    "Slovenia": ["slovenia", "slovenian"],
    "Somalia": ["somalia", "somali"],
    "South Africa": ["south africa", "south african"],
    "South Korea": ["south korea", "korea", "korean", "republic of korea"],
    "South Sudan": ["south sudan", "south sudanese"],
    "Spain": ["spain", "spanish"],
    "Sri Lanka": ["sri lanka", "sri lankan"],
    "Sudan": ["sudan", "sudanese"],
    "Suriname": ["suriname", "surinamese"],
    "Sweden": ["sweden", "swedish"],
    "Switzerland": ["switzerland", "swiss"],
    "Syria": ["syria", "syrian"],
    "Taiwan": ["taiwan", "taiwanese"],
    "Tajikistan": ["tajikistan", "tajik"],
    "Tanzania": ["tanzania", "tanzanian"],
    "Thailand": ["thailand", "thai"],
    "Timor-Leste": ["timor-leste", "east timor"],
    "Togo": ["togo", "togolese"],
    "Tunisia": ["tunisia", "tunisian"],
    "Turkey": ["turkey", "turkish", "türkiye", "turkiye"],
    "Uganda": ["uganda", "ugandan"],
    "Ukraine": ["ukraine", "ukrainian"],
    "United Arab Emirates": ["united arab emirates", "uae", "emirati"],
    "United Kingdom": ["united kingdom", "uk", "britain", "british", "england", "scotland", "wales"],
    "United States": ["united states", "usa", "u.s.", "u.s.a.", "american"],
    "Uruguay": ["uruguay", "uruguayan"],
    "Uzbekistan": ["uzbekistan", "uzbek"],
    "Venezuela": ["venezuela", "venezuelan"],
    "Vietnam": ["vietnam", "viet nam", "vietnamese"],
    "Yemen": ["yemen", "yemeni"],
    "Zambia": ["zambia", "zambian"],
    "Zimbabwe": ["zimbabwe", "zimbabwean"],
}

# Optional: terms to ignore when they are too ambiguous on their own.
# For example "georgia" can mean the US state.
AMBIGUOUS_TERMS = {
    "georgia": "Georgia",
    "guinea": "Guinea",
    "chad": "Chad",
    "jordan": "Jordan",
    "mali": "Mali",
    "niger": "Niger",
}

def normalize_text(text: str) -> str:
    if pd.isna(text):
        return ""
    text = str(text).lower()
    text = text.replace("’", "'")
    text = re.sub(r"\s+", " ", text)
    return text.strip()

def compile_country_patterns(country_aliases: dict):
    compiled = {}
    for country, aliases in country_aliases.items():
        pats = []
        for alias in aliases:
            alias_norm = normalize_text(alias)
            pats.append(re.compile(rf"(?<!\w){re.escape(alias_norm)}(?!\w)", re.IGNORECASE))
        compiled[country] = pats
    return compiled

COUNTRY_PATTERNS = compile_country_patterns(COUNTRY_ALIASES)

def infer_countries_from_text(title: str, description: str):
    text = normalize_text(f"{title or ''} {description or ''}")
    matches = []

    for country, patterns in COUNTRY_PATTERNS.items():
        for pat in patterns:
            if pat.search(text):
                matches.append(country)
                break

    # Light disambiguation for especially ambiguous single-term matches
    # Keeps the country if there are stronger clues nearby.
    filtered = []
    for country in matches:
        keep = True
        if country in {"Georgia", "Jordan", "Chad", "Mali", "Niger", "Guinea"}:
            stronger_aliases = [a for a in COUNTRY_ALIASES[country] if a.lower() != country.lower()]
            if country.lower() in text and not any(sa.lower() in text for sa in stronger_aliases):
                # leave it in, but this is the weakest confidence case
                pass
        if keep:
            filtered.append(country)

    filtered = sorted(set(filtered))
    return filtered

def country_confidence(countries, title, description):
    if not countries:
        return "none"
    text = normalize_text(f"{title or ''} {description or ''}")
    strong_count = 0
    for country in countries:
        aliases = [a.lower() for a in COUNTRY_ALIASES[country]]
        if any(alias in text for alias in aliases if " " in alias or alias not in AMBIGUOUS_TERMS):
            strong_count += 1
    if strong_count >= 1:
        return "high"
    return "medium"

# Apply to dataframe
df["country_matches"] = df.apply(
    lambda r: infer_countries_from_text(r.get("title"), r.get("description")),
    axis=1
)

df["country_match_count"] = df["country_matches"].apply(len)
df["primary_country"] = df["country_matches"].apply(lambda x: x[0] if x else None)
df["country_match_confidence"] = df.apply(
    lambda r: country_confidence(r["country_matches"], r.get("title"), r.get("description")),
    axis=1
)

# Optional JSON-string version for export
df["country_matches_json"] = df["country_matches"].apply(json.dumps)

# Quick preview
display(
    df[
        ["title", "primary_country", "country_matches", "country_match_confidence", "video_url"]
    ].head(20)
)

print(df["primary_country"].value_counts(dropna=False).head(30))

,title,primary_country,country_matches,country_match_confidence,video_url
0,The Belém Call: Mobilizing Finance for Forest ...,None,[],none,https://www.youtube.com/watch?v=8dChEJa-Or8
1,Indigenous NDCs for Climate Justice in the Ama...,Brazil,"[Brazil, Colombia]",high,https://www.youtube.com/watch?v=c3YPYIacZTA
2,Why are common reporting standards important f...,None,[],none,https://www.youtube.com/watch?v=SaL_mi3ySlI
3,Why are organisational financial capacities cr...,None,[],none,https://www.youtube.com/watch?v=jttqouosNFM
4,What is the meaning that the Amazon forest hol...,Brazil,[Brazil],high,https://www.youtube.com/watch?v=0NZkTcKpYRE
5,Why investing in Indigenous women?,Panama,[Panama],high,https://www.youtube.com/watch?v=1eVaPVbcUPk
6,Gender and biodiversity: How Indigenous and Lo...,None,[],none,https://www.youtube.com/watch?v=egZ2DK7KOlM
7,How Indigenous and local community women safeg...,None,[],none,https://www.youtube.com/watch?v=sLYP3DaT844
8,Women Ancestral Knowledge - GATC & TF campaign,None,[],none,https://www.youtube.com/watch?v=viy6c6QTMXc
9,Community Land Forest Concessions (CFCL) in th...,Democratic Republic of the Congo,[Democratic Republic of the Congo],high,https://www.youtube.com/watch?v=JWvbF0ysyWQ
10,Ecuador - Escuela de Formación de Monitores Te...,Ecuador,[Ecuador],high,https://www.youtube.com/watch?v=Cd4oQJCUQR0
11,"""Territory Is Life"" - Collective Land Titling ...",Colombia,[Colombia],high,https://www.youtube.com/watch?v=fdIdpdRRomM
12,Who We Are,None,[],none,https://www.youtube.com/watch?v=AZ13K-kg_mY
13,Leading the Way: How Indigenous Youth Combat C...,None,[],none,https://www.youtube.com/watch?v=A_-KKbWu8Tk
14,Inter-State Movement of Babassu Coconut Breake...,Brazil,[Brazil],high,https://www.youtube.com/watch?v=kJ8_FZUXUWQ
15,What kind of world will you help build?,None,[],none,https://www.youtube.com/watch?v=lVCovWt_ye8
16,The fate of our future hinges on how we treat ...,None,[],none,https://www.youtube.com/watch?v=XKiyqeXIIF0
17,"Our Executive Director, Nonette Royo, at the H...",None,[],none,https://www.youtube.com/watch?v=ZuCr_z8JCBk
18,Have you ever tried explaining your missions t...,None,[],none,https://www.youtube.com/watch?v=rSNx77gf5nk
19,Climate Funding and COP28 : Turning Pledges in...,None,[],none,https://www.youtube.com/watch?v=jXIrTdHO5bg

primary_country
None                                84
Indonesia                           15
Panama                               9
Liberia                              5
Colombia                             4
Guyana                               4
Brazil                               4
Belize                               4
Democratic Republic of the Congo     3
Mali                                 3
Peru                                 3
India                                2
Ecuador                              2
Nepal                                2
China                                1
Guatemala                            1
Portugal                             1
Mozambique                           1
Name: count, dtype: int64

In [13]:
import pandas as pd

# Columns that are usually the most useful for analysis
preferred_cols = [
    "video_id",
    "video_url",
    "title",
    "description",
    "published_at",
    "duration_iso8601",
    "view_count",
    "like_count",
    "comment_count",
    "category_title",
    "default_language",
    "default_audio_language",
    "topic_categories",
    "thumb_high",
    "channel_title",
    "channel_subscriber_count",
    "privacy_status",
    "embeddable",
    "made_for_kids",
    "playlist_position",
]

# Keep only columns that actually exist
preferred_cols = [c for c in preferred_cols if c in df.columns]

df_clean = df[preferred_cols].copy()

# Drop columns that are entirely empty after selection
def has_real_content(series):
    s = series.astype(str).str.strip()
    return (~series.isna() & ~s.isin(["", "nan", "None", "[]", "{}"])).any()

df_clean = df_clean[[c for c in df_clean.columns if has_real_content(df_clean[c])]]

# Optional numeric conversion
for col in ["view_count", "like_count", "comment_count", "channel_subscriber_count", "playlist_position"]:
    if col in df_clean.columns:
        df_clean[col] = pd.to_numeric(df_clean[col], errors="coerce")

# Optional datetime conversion
if "published_at" in df_clean.columns:
    df_clean["published_at"] = pd.to_datetime(df_clean["published_at"], errors="coerce")

print("Kept columns:")
print(df_clean.columns.tolist())

display(df_clean.head(10))

Kept columns:
['video_id', 'video_url', 'title', 'description', 'published_at', 'duration_iso8601', 'view_count', 'like_count', 'comment_count', 'category_title', 'default_language', 'default_audio_language', 'topic_categories', 'thumb_high', 'channel_title', 'channel_subscriber_count', 'privacy_status', 'embeddable', 'made_for_kids', 'playlist_position']

,video_id,video_url,title,description,published_at,duration_iso8601,view_count,like_count,comment_count,category_title,default_language,default_audio_language,topic_categories,thumb_high,channel_title,channel_subscriber_count,privacy_status,embeddable,made_for_kids,playlist_position
0,8dChEJa-Or8,https://www.youtube.com/watch?v=8dChEJa-Or8,The Belém Call: Mobilizing Finance for Forest ...,Join us today for a webinar exploring the Belé...,2026-01-28 04:50:10+00:00,PT1H30M49S,18,0,0,Entertainment,en,en,"[""https://en.wikipedia.org/wiki/Society""]",https://i.ytimg.com/vi/8dChEJa-Or8/hqdefault.jpg,Tenure Facility,176,public,True,False,0
1,c3YPYIacZTA,https://www.youtube.com/watch?v=c3YPYIacZTA,Indigenous NDCs for Climate Justice in the Ama...,Made with Restream. Livestream on 30+ platform...,2025-07-18 02:22:17+00:00,PT1H10M30S,6,0,0,Entertainment,en,en,"[""https://en.wikipedia.org/wiki/Society""]",https://i.ytimg.com/vi/c3YPYIacZTA/hqdefault.jpg,Tenure Facility,176,public,True,False,1
2,SaL_mi3ySlI,https://www.youtube.com/watch?v=SaL_mi3ySlI,Why are common reporting standards important f...,,2025-01-27 09:38:59+00:00,PT3M33S,46,0,0,Entertainment,en,en,"[""https://en.wikipedia.org/wiki/Society""]",https://i.ytimg.com/vi/SaL_mi3ySlI/hqdefault.jpg,Tenure Facility,176,public,True,True,2
3,jttqouosNFM,https://www.youtube.com/watch?v=jttqouosNFM,Why are organisational financial capacities cr...,The climate and biodiversity crises have force...,2025-01-24 08:29:08+00:00,PT1M55S,202,1,0,Entertainment,en,en,"[""https://en.wikipedia.org/wiki/Society""]",https://i.ytimg.com/vi/jttqouosNFM/hqdefault.jpg,Tenure Facility,176,public,True,True,3
4,0NZkTcKpYRE,https://www.youtube.com/watch?v=0NZkTcKpYRE,What is the meaning that the Amazon forest hol...,Sandra Ribeiro (left) and Helena Gomes (right)...,2024-07-23 07:26:38+00:00,PT45S,48,0,0,Entertainment,en,en,"[""https://en.wikipedia.org/wiki/Lifestyle_(soc...",https://i.ytimg.com/vi/0NZkTcKpYRE/hqdefault.jpg,Tenure Facility,176,public,True,True,4
5,1eVaPVbcUPk,https://www.youtube.com/watch?v=1eVaPVbcUPk,Why investing in Indigenous women?,"Did you know that traditional knowledge, often...",2024-07-18 08:11:34+00:00,PT1M31S,166,2,0,Entertainment,en,en,"[""https://en.wikipedia.org/wiki/Society""]",https://i.ytimg.com/vi/1eVaPVbcUPk/hqdefault.jpg,Tenure Facility,176,public,True,True,5
6,egZ2DK7KOlM,https://www.youtube.com/watch?v=egZ2DK7KOlM,Gender and biodiversity: How Indigenous and Lo...,Indigenous women's knowledge is rooted in a de...,2024-06-17 07:10:37+00:00,PT1H17M9S,416,0,0,Entertainment,en,en,"[""https://en.wikipedia.org/wiki/Knowledge""]",https://i.ytimg.com/vi/egZ2DK7KOlM/hqdefault.jpg,Tenure Facility,176,public,True,True,6
7,sLYP3DaT844,https://www.youtube.com/watch?v=sLYP3DaT844,How Indigenous and local community women safeg...,Turn your videos into live streams with Restre...,2024-06-14 02:33:28+00:00,PT1H14M33S,130,0,0,Entertainment,en,en,"[""https://en.wikipedia.org/wiki/Society""]",https://i.ytimg.com/vi/sLYP3DaT844/hqdefault.jpg,Tenure Facility,176,public,True,False,7
8,viy6c6QTMXc,https://www.youtube.com/watch?v=viy6c6QTMXc,Women Ancestral Knowledge - GATC & TF campaign,We’re celebrating the powerful role of Indigen...,2024-06-10 13:57:40+00:00,PT1M31S,924,0,0,Entertainment,en,en,"[""https://en.wikipedia.org/wiki/Society""]",https://i.ytimg.com/vi/viy6c6QTMXc/hqdefault.jpg,Tenure Facility,176,public,True,True,8
9,JWvbF0ysyWQ,https://www.youtube.com/watch?v=JWvbF0ysyWQ,Community Land Forest Concessions (CFCL) in th...,,2024-06-10 13:14:21+00:00,PT2M13S,153,1,0,Entertainment,it,en,"[""https://en.wikipedia.org/wiki/Society""]",https://i.ytimg.com/vi/JWvbF0ysyWQ/hqdefault.jpg,Tenure Facility,176,public,True,True,9

## 12. Save outputs

In [14]:
csv_path = f"{SAVE_PREFIX}_videos_full.csv"
json_path = f"{SAVE_PREFIX}_videos_full.json"
channel_json_path = f"{SAVE_PREFIX}_channel_full.json"

df.to_csv(csv_path, index=False, encoding="utf-8-sig")
df.to_json(json_path, orient="records", force_ascii=False, indent=2)

with open(channel_json_path, "w", encoding="utf-8") as f:
    json.dump(channel_resource, f, ensure_ascii=False, indent=2)

print("Saved:")
print(csv_path)
print(json_path)
print(channel_json_path)
print("Rows:", len(df))

Saved:
tenure_facility_videos_full.csv
tenure_facility_videos_full.json
tenure_facility_channel_full.json
Rows: 148

## 13. Optional sanity checks

In [15]:
print("Missing descriptions:", df["description"].isna().sum())
print("Missing tags:", df["tags"].isna().sum())
print("Privacy status counts:")
print(df["privacy_status"].value_counts(dropna=False))

print("\nTop 15 by views:")
display(
    df[["title", "view_count", "published_at", "duration_iso8601", "video_url"]]
    .assign(view_count_num=pd.to_numeric(df["view_count"], errors="coerce"))
    .sort_values("view_count_num", ascending=False)
    .drop(columns="view_count_num")
    .head(15)
)

Missing descriptions: 0
Missing tags: 0
Privacy status counts:
privacy_status
public    148
Name: count, dtype: int64

Top 15 by views:

,title,view_count,published_at,duration_iso8601,video_url
21,Kynan Tegar: International Day of the World's ...,1206,2023-08-09T03:00:07Z,PT1M31S,https://www.youtube.com/watch?v=7K12aIVpTOM
81,"Opening Ceremony - Mayejak Blessing, Jalacte, ...",1152,2022-02-25T12:24:18Z,PT15M1S,https://www.youtube.com/watch?v=MZP06JEuTdo
8,Women Ancestral Knowledge - GATC & TF campaign,924,2024-06-10T13:57:40Z,PT1M31S,https://www.youtube.com/watch?v=viy6c6QTMXc
147,This is why the Tenure matters,730,2018-10-12T16:20:24Z,PT2M36S,https://www.youtube.com/watch?v=l6nBCtnHW1c
14,Inter-State Movement of Babassu Coconut Breake...,445,2024-04-17T12:27:48Z,PT1M43S,https://www.youtube.com/watch?v=kJ8_FZUXUWQ
12,Who We Are,430,2024-04-30T20:54:19Z,PT2M12S,https://www.youtube.com/watch?v=AZ13K-kg_mY
6,Gender and biodiversity: How Indigenous and Lo...,416,2024-06-17T07:10:37Z,PT1H17M9S,https://www.youtube.com/watch?v=egZ2DK7KOlM
22,Eli Virkina: International Day of the World's ...,412,2023-08-09T03:00:06Z,PT1M58S,https://www.youtube.com/watch?v=DBR_xzrivTI
87,San Benito Poite Village - the auto-deliminati...,348,2022-02-10T09:51:06Z,PT3M26S,https://www.youtube.com/watch?v=uFi_Cuf-jhE
146,Our Territory,271,2020-03-09T09:37:30Z,PT8M48S,https://www.youtube.com/watch?v=EhioEX10DNo
108,Indigenous Peoples forests governance: a funda...,219,2021-05-03T09:26:33Z,PT1H31M15S,https://www.youtube.com/watch?v=Y-xoICl8egg
33,Tenure Tales - Guyana,210,2023-02-20T09:48:53Z,PT6M54S,https://www.youtube.com/watch?v=x76zlAXw7wY
125,Stories of resilience- Nepal,203,2020-11-25T11:57:46Z,PT3M55S,https://www.youtube.com/watch?v=wlZUdRYUoxQ
3,Why are organisational financial capacities cr...,202,2025-01-24T08:29:08Z,PT1M55S,https://www.youtube.com/watch?v=jttqouosNFM
5,Why investing in Indigenous women?,166,2024-07-18T08:11:34Z,PT1M31S,https://www.youtube.com/watch?v=1eVaPVbcUPk